--[[
    Copyright (C) 2026 HarpyWar (harpywar@gmail.com)
    
    This file is a part of the PvPGN Project http://pvpgn.pro
    Licensed under the same terms as Lua itself.
]]--
-- ============================================================================
-- COMANDO MENU PERSONALIZADO
-- ============================================================================
function command_menu(account, text)
    api.message_send_text(account.name, message_type_info, nil, "=== Comandos Personalizados ===")
    
    -- Comandos de admin/moderador
    if math_and(account_get_auth_command_groups(account.name), 4) ~= 0 then
        api.message_send_text(account.name, message_type_info, nil, "/upload")
        api.message_send_text(account.name, message_type_info, nil, "/dl")
        api.message_send_text(account.name, message_type_info, nil, "/dllist")
        api.message_send_text(account.name, message_type_info, nil, "/dlconfig")
        api.message_send_text(account.name, message_type_info, nil, "/dltest")
        api.message_send_text(account.name, message_type_info, nil, "/botimmunity")
        api.message_send_text(account.name, message_type_info, nil, "/redirect")
        api.message_send_text(account.name, message_type_info, nil, "/kick")
        api.message_send_text(account.name, message_type_info, nil, "/ban")
        api.message_send_text(account.name, message_type_info, nil, "/unban")
        api.message_send_text(account.name, message_type_info, nil, "/serverban")
        api.message_send_text(account.name, message_type_info, nil, "/ipscan")
        api.message_send_text(account.name, message_type_info, nil, "/kill")
        api.message_send_text(account.name, message_type_info, nil, "/killsession")
        api.message_send_text(account.name, message_type_info, nil, "/announce")
        api.message_send_text(account.name, message_type_info, nil, "/shutdown")
        api.message_send_text(account.name, message_type_info, nil, "/lock")
        api.message_send_text(account.name, message_type_info, nil, "/unlock")
        api.message_send_text(account.name, message_type_info, nil, "/mute")
        api.message_send_text(account.name, message_type_info, nil, "/unmute")
        api.message_send_text(account.name, message_type_info, nil, "/ipban")
        api.message_send_text(account.name, message_type_info, nil, "/set")
        api.message_send_text(account.name, message_type_info, nil, "/rehash")
        api.message_send_text(account.name, message_type_info, nil, "/find")
        api.message_send_text(account.name, message_type_info, nil, "/save")
        api.message_send_text(account.name, message_type_info, nil, "/clearstats")
        api.message_send_text(account.name, message_type_info, nil, "/connections")
        api.message_send_text(account.name, message_type_info, nil, "/admins")
        api.message_send_text(account.name, message_type_info, nil, "/ladderactivate")
        api.message_send_text(account.name, message_type_info, nil, "/ladderinfo")
        api.message_send_text(account.name, message_type_info, nil, "/netinfo")
        api.message_send_text(account.name, message_type_info, nil, "/addacct")
        api.message_send_text(account.name, message_type_info, nil, "/chpass")
        api.message_send_text(account.name, message_type_info, nil, "/watchall")
        api.message_send_text(account.name, message_type_info, nil, "/unwatchall")
        api.message_send_text(account.name, message_type_info, nil, "/moderate")
        api.message_send_text(account.name, message_type_info, nil, "/topic")
        api.message_send_text(account.name, message_type_info, nil, "/aop")
        api.message_send_text(account.name, message_type_info, nil, "/op")
        api.message_send_text(account.name, message_type_info, nil, "/deop")
        api.message_send_text(account.name, message_type_info, nil, "/tmpop")
        api.message_send_text(account.name, message_type_info, nil, "/vop")
        api.message_send_text(account.name, message_type_info, nil, "/voice")
        api.message_send_text(account.name, message_type_info, nil, "/devoice")
        api.message_send_text(account.name, message_type_info, nil, "/flag")
        api.message_send_text(account.name, message_type_info, nil, "/tag")
        api.message_send_text(account.name, message_type_info, nil, "/alert")
        api.message_send_text(account.name, message_type_info, nil, "/realmann")
        api.message_send_text(account.name, message_type_info, nil, "/admin")
        api.message_send_text(account.name, message_type_info, nil, "/operator")
        api.message_send_text(account.name, message_type_info, nil, "/command_groups")
    end

    -- Comandos para todos
    api.message_send_text(account.name, message_type_info, nil, "/slots")
    api.message_send_text(account.name, message_type_info, nil, "/rehost")
    api.message_send_text(account.name, message_type_info, nil, "/unhost")
    api.message_send_text(account.name, message_type_info, nil, "/botstats")
    api.message_send_text(account.name, message_type_info, nil, "/quiz")
    api.message_send_text(account.name, message_type_info, nil, "/whois")
    api.message_send_text(account.name, message_type_info, nil, "/w")
    api.message_send_text(account.name, message_type_info, nil, "/r")
    api.message_send_text(account.name, message_type_info, nil, "/ignore")
    api.message_send_text(account.name, message_type_info, nil, "/unignore")
    api.message_send_text(account.name, message_type_info, nil, "/away")
    api.message_send_text(account.name, message_type_info, nil, "/dnd")
    api.message_send_text(account.name, message_type_info, nil, "/who")
    api.message_send_text(account.name, message_type_info, nil, "/stats")
    api.message_send_text(account.name, message_type_info, nil, "/users")
    api.message_send_text(account.name, message_type_info, nil, "/time")
    api.message_send_text(account.name, message_type_info, nil, "/join")
    api.message_send_text(account.name, message_type_info, nil, "/rejoin")
    api.message_send_text(account.name, message_type_info, nil, "/me")
    api.message_send_text(account.name, message_type_info, nil, "/whoami")
    api.message_send_text(account.name, message_type_info, nil, "/uptime")
    api.message_send_text(account.name, message_type_info, nil, "/version")
    api.message_send_text(account.name, message_type_info, nil, "/lusers")
    api.message_send_text(account.name, message_type_info, nil, "/games")
    api.message_send_text(account.name, message_type_info, nil, "/channels")
    api.message_send_text(account.name, message_type_info, nil, "/finger")
    api.message_send_text(account.name, message_type_info, nil, "/news")
    api.message_send_text(account.name, message_type_info, nil, "/logout")
    api.message_send_text(account.name, message_type_info, nil, "/watch")
    api.message_send_text(account.name, message_type_info, nil, "/unwatch")
    api.message_send_text(account.name, message_type_info, nil, "/gameinfo")
    api.message_send_text(account.name, message_type_info, nil, "/timer")
    api.message_send_text(account.name, message_type_info, nil, "/quota")
    api.message_send_text(account.name, message_type_info, nil, "/friends")
    api.message_send_text(account.name, message_type_info, nil, "/mail")
    api.message_send_text(account.name, message_type_info, nil, "/motd")
    api.message_send_text(account.name, message_type_info, nil, "/tos")
    api.message_send_text(account.name, message_type_info, nil, "/clan")
    api.message_send_text(account.name, message_type_info, nil, "/ping")
    api.message_send_text(account.name, message_type_info, nil, "/icon")
    api.message_send_text(account.name, message_type_info, nil, "/language")

    return 0
end